FROM node:20-alpine

WORKDIR /app

COPY apps/backend/package*.json ./

RUN npm install

COPY apps/backend .

RUN chmod +x node_modules/.bin/prisma

RUN npx prisma generate

EXPOSE 5555

CMD ["npm", "start"]